### ISSUE TITLE
Cannot install bob.db.cbsr-nir-vis-2

### ISSUE THREAD

**Issue by ShangWeiKuo** [bioidiap/bob.db.cbsr_nir_vis_2#1]
Hello. I've installed bob.extension with the command **pip install bob.extension**

However. When I tried installing bob.db.cbsr-nir-vis-2 with the command **pip install bob.db.cbsr-nir-vis-2**, I got the error message **ImportError: cannot import name 'Extension' from 'bob.extension' (/tmp/pip-build-env-9e708cku/overlay/lib/python3.8/site-packages/bob/extension/__init__.py)** as the contents below:
<br>
```
Looking in indexes: https://pypi.org/simple, https://pypi.ngc.nvidia.com
Collecting bob.extension
  Downloading bob.extension-7.0.3.zip (65 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 65.2/65.2 kB 2.3 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: setuptools in /opt/conda/lib/python3.8/site-packages (from bob.extension) (59.5.0)
Collecting click-plugins
  Downloading click_plugins-1.1.1-py2.py3-none-any.whl (7.5 kB)
Requirement already satisfied: click>=8 in /opt/conda/lib/python3.8/site-packages (from bob.extension) (8.0.4)
Building wheels for collected packages: bob.extension
  Building wheel for bob.extension (pyproject.toml) ... done
  Created wheel for bob.extension: filename=bob.extension-7.0.3-py3-none-any.whl size=41460 sha256=2658a2c52a9fe1a5b42ea7919881307464a3c45d84cc7a5c2f1c7a3e0ab44f8c
  Stored in directory: /tmp/pip-ephem-wheel-cache-7x8_685g/wheels/73/7c/e9/e038994888b3c4b25e4e81e9e424a411bdac148f3e6e6fad6f
Successfully built bob.extension
Installing collected packages: click-plugins, bob.extension
Successfully installed bob.extension-7.0.3 click-plugins-1.1.1
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv

[notice] A new release of pip available: 22.1.2 -> 23.1.2
[notice] To update, run: pip install --upgrade pip
root@pai2-gworker2-node:/CGMHtest3/aion_data# pip install bob.db.cbsr-nir-vis-2
Looking in indexes: https://pypi.org/simple, https://pypi.ngc.nvidia.com
Collecting bob.db.cbsr-nir-vis-2
  Downloading bob.db.cbsr_nir_vis_2-2.0.7.zip (29 kB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: setuptools in /opt/conda/lib/python3.8/site-packages (from bob.db.cbsr-nir-vis-2) (59.5.0)
Collecting bob.db.base
  Downloading bob.db.base-3.2.0.zip (366 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 366.9/366.9 kB 6.0 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting sqlalchemy
  Downloading SQLAlchemy-2.0.12-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (2.8 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.8/2.8 MB 36.2 MB/s eta 0:00:00
Collecting bob.io.image
  Downloading bob.io.image-2.5.1.zip (725 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 725.5/725.5 kB 375.6 MB/s eta 0:00:00
  Installing build dependencies ... error
  error: subprocess-exited-with-error
  
  × pip subprocess to install build dependencies did not run successfully.
  │ exit code: 1
  ╰─> [57 lines of output]
      Looking in indexes: https://pypi.org/simple, https://pypi.ngc.nvidia.com, https://pypi.ngc.nvidia.com
      Collecting setuptools
        Downloading setuptools-67.7.2-py3-none-any.whl (1.1 MB)
           ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.1/1.1 MB 8.9 MB/s eta 0:00:00
      Collecting wheel
        Downloading wheel-0.40.0-py3-none-any.whl (64 kB)
           ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 64.5/64.5 kB 238.1 MB/s eta 0:00:00
      Collecting bob.extension
        Downloading bob.extension-7.0.3.zip (65 kB)
           ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 65.2/65.2 kB 242.8 MB/s eta 0:00:00
        Installing build dependencies: started
        Installing build dependencies: finished with status 'done'
        Getting requirements to build wheel: started
        Getting requirements to build wheel: finished with status 'done'
        Preparing metadata (pyproject.toml): started
        Preparing metadata (pyproject.toml): finished with status 'done'
      Collecting bob.blitz
        Downloading bob.blitz-2.0.24.zip (123 kB)
           ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 123.1/123.1 kB 306.6 MB/s eta 0:00:00
        Installing build dependencies: started
        Installing build dependencies: still running...
        Installing build dependencies: finished with status 'done'
        Getting requirements to build wheel: started
        Getting requirements to build wheel: finished with status 'error'
        error: subprocess-exited-with-error
      
        × Getting requirements to build wheel did not run successfully.
        │ exit code: 1
        ╰─> [15 lines of output]
            Traceback (most recent call last):
              File "/tmp/tmpcek_pkkx", line 363, in <module>
                main()
              File "/tmp/tmpcek_pkkx", line 345, in main
                json_out['return_val'] = hook(**hook_input['kwargs'])
              File "/tmp/tmpcek_pkkx", line 130, in get_requires_for_build_wheel
                return hook(config_settings)
              File "/tmp/pip-build-env-9e708cku/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 341, in get_requires_for_build_wheel
                return self._get_build_requires(config_settings, requirements=['wheel'])
              File "/tmp/pip-build-env-9e708cku/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 323, in _get_build_requires
                self.run_setup()
              File "/tmp/pip-build-env-9e708cku/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 338, in run_setup
                exec(code, locals())
              File "<string>", line 9, in <module>
            ImportError: cannot import name 'Extension' from 'bob.extension' (/tmp/pip-build-env-9e708cku/overlay/lib/python3.8/site-packages/bob/extension/__init__.py)
            [end of output]
      
        note: This error originates from a subprocess, and is likely not a problem with pip.
      error: subprocess-exited-with-error
      
      × Getting requirements to build wheel did not run successfully.
      │ exit code: 1
      ╰─> See above for output.
      
      note: This error originates from a subprocess, and is likely not a problem with pip.
      
      [notice] A new release of pip available: 22.1.2 -> 23.1.2
      [notice] To update, run: pip install --upgrade pip
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× pip subprocess to install build dependencies did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

[notice] A new release of pip available: 22.1.2 -> 23.1.2
[notice] To update, run: pip install --upgrade pip
```

How should I do to deal with the problem ?

Thank you for your help in advance.

**Comment by dvirla** [comment]
Did anyone solve this issue?
